### PR TITLE
Completely rewrite jopa

### PR DESCRIPTION
**Pull request by m13253**
- Uses PulseAudio async API, with better control of latency
- Supports playing, recording, and monitoring
- Supports dynamic sample rate & buffer size switching
- Fixes various race conditions, eliminating various crashes

### CODE REVIEW

**Comment by cjxgm** [comment]
I'm currently not maintaining this project, maybe you can take over?

**Comment by cjxgm** [comment]
Wait, why did you send pull request downstream?

**Comment by m13253** [comment]
> Wait, why did you send pull request downstream?

I just want you to sync over my code. xD

**Comment by cjxgm** [comment]
I should have rebased it if I knew that earlier.

Any way, I use Jack less frequently than before, and can just bear with the pulse over jack plugin.
This fork will be removed when I clean up my unmaintained/unused repos/forks in the near future.

**Pull request merged**
